/**
 * @author Tobias
 */

package Tobias;

import static Tobias.ImageOverlay.overlayImages;
import static Tobias.ImageOverlay.readImage;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

import Andreas.QuizGUI2;


public class DELETE_GUI_Background extends javax.swing.JFrame {
    SoundPlayer player1 = new SoundPlayer();
    Round round = new Round();
    ImageOverlay imageoverlay = new ImageOverlay();
    String bg_fileName; 
    String star_fileName; 
    Random pos = new Random(); 
    int posX;
    int posY;
    
// timer variables
    private JLabel label;
    private Timer timer;
    private final int COUNT_TIME = 4;
    private int counter; // the duration
    private final int DELAY = 1000; // every 1 second
    private boolean timeUp = false;
   
    
    
    public DELETE_GUI_Background() {
        
        initComponents();
        
        //-Place star randomly on screen
        jLabel_star.setLocation(randomPosX(), randomPosY());
        
        //- Change background image
        bg_fileName = "./art/images/backgroundImages/bg_london.jpg";
        ImageIcon background = new ImageIcon(bg_fileName);
        jLabel_background.setIcon(background);
        //----------------------------------------------
        
        //-Change star image
        star_fileName = "./art/images/icons/star.png";
        ImageIcon star = new ImageIcon(star_fileName);
        jLabel_star.setIcon(star);
        //---------------------------------------------
        
        
        
        //-start countdown
        setCountDown();
        
        /*player1.loadSound("./art/sound/ItsBeenSoLong.wav");
        player1.playSound();
        player1.stopSound(); */

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_countDown = new javax.swing.JLabel();
        jLabel_star = new javax.swing.JLabel();
        jLabel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_countDown.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_countDown.setFont(new java.awt.Font("Tunga", 0, 24)); // NOI18N
        jLabel_countDown.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_countDown.setText("countdown");
        jLabel_countDown.setOpaque(true);
        getContentPane().add(jLabel_countDown);
        jLabel_countDown.setBounds(690, 530, 100, 30);

        jLabel_star.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\icons\\star.png")); // NOI18N
        jLabel_star.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_starMouseClicked(evt);
            }
        });
        getContentPane().add(jLabel_star);
        jLabel_star.setBounds(340, 260, 60, 70);

        jLabel_background.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\backgroundImages\\bg_london.jpg")); // NOI18N
        getContentPane().add(jLabel_background);
        jLabel_background.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_starMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_starMouseClicked
        System.out.println("Star clicked!");
        QuizGUI2 quiz = new QuizGUI2();
        quiz.setVisible(true);
    }//GEN-LAST:event_jLabel_starMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_Background.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_GUI_Background().setVisible(true);
            }
        });
    }
    
    public int randomPosX() {
        posX = pos.nextInt(700)+30;
        return posX;
    }
    
    public int randomPosY() {
        posY = pos.nextInt(500)+30;
        return posY;
    }
    
    public void setCountDown() {
        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent event) {
                timeUp = false;
                System.out.println("TimeUp is: " + timeUp);
                if (counter == 0) {
                    round.subtractRound(-1);
                    timeUp = true;
                    System.out.println("TimeUp is: " + timeUp);
                    jLabel_countDown.setText("Time is up!");
                    jLabel_star.setLocation(randomPosX(), randomPosY());
                    counter = COUNT_TIME;
                    
                } else {
                    jLabel_countDown.setText(counter-1 + "sec");
                    counter--;
                }
            System.out.println("Counter is: " + counter);  
            } 
        };
        
        counter = COUNT_TIME;
        timer = new Timer(DELAY, action);   
        timer.setInitialDelay(0);
        timer.setRepeats(true);
        timer.start();
        setVisible(true);
    }
    
    public void timeIsUp() {
        //jLabel_star.setLocation(randomPosX(), randomPosY());
        timer.stop();
        timeUp = false;
        //timer.restart();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_background;
    private javax.swing.JLabel jLabel_countDown;
    private javax.swing.JLabel jLabel_star;
    // End of variables declaration//GEN-END:variables
}
