/**
 * @author Tobias
 */
package Tobias;

import java.awt.Color;
import javax.swing.ImageIcon;
//public class GUI_CharacterSelection extends javax.swing.JFrame {

public class DELETE_GUI_CharacterSelection extends GUI_Main {
    private final ImageIcon man_unselected_icon = new ImageIcon("./art/images/character/man_1_unselected.png");
    private final ImageIcon man_entered_icon = new ImageIcon("./art/images/character/man_1_entered.png");
    private final ImageIcon man_selected_icon = new ImageIcon("./art/images/character/man_1_selected.png");
    
    private final ImageIcon woman_unselected_icon = new ImageIcon("./art/images/character/woman_1_unselected.png");
    private final ImageIcon woman_entered_icon = new ImageIcon("./art/images/character/woman_1_entered.png");
    private final ImageIcon woman_selected_icon = new ImageIcon("./art/images/character/woman_1_selected.png");
    
    private final ImageIcon child_unselected_icon = new ImageIcon ("./art/images/character/child_1_unselected.png");
    private final ImageIcon child_entered_icon = new ImageIcon ("./art/images/character/child_1_entered.png");
    private final ImageIcon child_selected_icon = new ImageIcon ("./art/images/character/child_1_selected.png");
    
    ImageIcon womanIcon = null;
    ImageIcon childIcon = null;
    
    private Boolean man_selected = false;
    private Boolean woman_selected = false;
    private Boolean child_selected = false;
    
    
    public DELETE_GUI_CharacterSelection() {
        initComponents();
        jLabel_next.setVisible(false);
        getContentPane().setBackground(Color.orange);
        //jLabel_background.
        //set character icons
        initIcons();
        checkForSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_man = new javax.swing.JLabel();
        jLabel_woman = new javax.swing.JLabel();
        jLabel_child = new javax.swing.JLabel();
        jLabel_choose1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabel_man.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\man_1.png")); // NOI18N
        jLabel_man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_manMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_manMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_manMousePressed(evt);
            }
        });

        jLabel_woman.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\woman_1.png")); // NOI18N
        jLabel_woman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_womanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_womanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_womanMousePressed(evt);
            }
        });

        jLabel_child.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\child_1.png")); // NOI18N
        jLabel_child.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_childMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_childMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_childMousePressed(evt);
            }
        });

        jLabel_choose1.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jLabel_choose1.setText("Please choose a character");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel_man)
                .addGap(78, 78, 78)
                .addComponent(jLabel_woman)
                .addGap(83, 83, 83)
                .addComponent(jLabel_child)
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(228, Short.MAX_VALUE)
                    .addComponent(jLabel_choose1)
                    .addGap(211, 211, 211)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_woman)
                    .addComponent(jLabel_child)
                    .addComponent(jLabel_man))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(jLabel_choose1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(431, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_manMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMouseEntered
        if (man_selected != true) {
        jLabel_man.setIcon(man_entered_icon);
        }
    }//GEN-LAST:event_jLabel_manMouseEntered

    private void jLabel_womanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMouseEntered
        if (woman_selected != true) {
        jLabel_woman.setIcon(woman_entered_icon);
        }
    }//GEN-LAST:event_jLabel_womanMouseEntered

    private void jLabel_childMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMouseEntered
        if (child_selected != true) {
        jLabel_child.setIcon(child_entered_icon);
        }
    }//GEN-LAST:event_jLabel_childMouseEntered

    private void jLabel_manMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMousePressed
        jLabel_man.setIcon(man_selected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);
        man_selected = true;
        woman_selected = false;
        child_selected = false;
        jLabel_next.setVisible(true);
    }//GEN-LAST:event_jLabel_manMousePressed

    private void jLabel_manMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMouseExited
        if (man_selected != true) {
        jLabel_man.setIcon(man_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_manMouseExited

    private void jLabel_womanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMouseExited
        if (woman_selected != true) {
        jLabel_woman.setIcon(woman_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_womanMouseExited

    private void jLabel_womanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMousePressed
        jLabel_woman.setIcon(woman_selected_icon);
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);
        woman_selected = true;
        man_selected = false;
        child_selected = false;
        jLabel_next.setVisible(true);
    }//GEN-LAST:event_jLabel_womanMousePressed

    private void jLabel_childMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMouseExited
        if (child_selected != true) {
        jLabel_child.setIcon(child_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_childMouseExited

    private void jLabel_childMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMousePressed
        jLabel_child.setIcon(child_selected_icon);
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        child_selected = true;
        man_selected = false;
        woman_selected = false;
        jLabel_next.setVisible(true);
        
    }//GEN-LAST:event_jLabel_childMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DELETE_GUI_CharacterSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DELETE_GUI_CharacterSelection().setVisible(true);
            }
        });
    }
    
    public void initIcons() {
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);
        jLabel_next.setVisible(false);
    }
    
    public void checkForSelection() {
        if (man_selected == true || woman_selected == true || child_selected == true) {
            jLabel_next.setVisible(true);
        }
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_child;
    private javax.swing.JLabel jLabel_choose1;
    private javax.swing.JLabel jLabel_man;
    private javax.swing.JLabel jLabel_woman;
    // End of variables declaration//GEN-END:variables
}
