/**
 * @author Tobias
 */
package Tobias;

import Daniel.Person;
import Daniel.Frame1;
import Daniel.FileHandler;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class GUI_Main extends javax.swing.JFrame {

    private final ImageIcon next_unselected_icon = new ImageIcon("./art/images/icons/next_unselected.png");
    private final ImageIcon next_entered_icon = new ImageIcon("./art/images/icons/next_entered.png");
    private final ImageIcon next_pressed_icon = new ImageIcon("./art/images/icons/next_pressed.png");
    Panel_Intro intro;
    Panel_QuizRules quizrules;
    Panel_CharacterSelection characterselection;
    Panel_TimerClick timerclick;
    Panel_Highscore highscore;
    Daniel.Panel_Login login;
    Daniel.Person person;
    
    String boardingNumber;
    String nickname;
    String password;

    Boolean wrongPassword = false;

    int currentPanel = 0;

    public GUI_Main() {

        initComponents();
        //init icons
        jLabel_next.setIcon(next_unselected_icon);
        jLabel_next.setVisible(true);

        //set background color
        getContentPane().setBackground(Color.orange);

        //init intro panel
        intro = new Panel_Intro();

        this.setLayout(new BorderLayout());
        this.add(intro, BorderLayout.CENTER);
        this.setVisible(true);

        //this.list = FileHandler.load("text.txt"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_next = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Destination Game");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_nextMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseReleased(evt);
            }
        });
        getContentPane().add(jLabel_next);
        jLabel_next.setBounds(650, 460, 110, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseEntered
        jLabel_next.setIcon(next_entered_icon);
    }//GEN-LAST:event_jLabel_nextMouseEntered

    private void jLabel_nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseExited
        jLabel_next.setIcon(next_unselected_icon);
    }//GEN-LAST:event_jLabel_nextMouseExited

    private void jLabel_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseClicked


    }//GEN-LAST:event_jLabel_nextMouseClicked

    private void jLabel_nextMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseReleased
        System.out.println("Released!");
        //currentPanel++;
        /*if (wrongPassword == true) {
            System.out.println("Wrong password!");
            currentPanel = 1;
            wrongPassword = false;
        }*/
    }//GEN-LAST:event_jLabel_nextMouseReleased

    private void jLabel_nextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMousePressed
        System.out.println("Pressed");
        currentPanel++;
        System.out.println("Current panel is: " + currentPanel);

        switch (currentPanel) 
        {
            case 0: //we start here in intro 
                break;
            case 1: //Login (import from Daniel package)
                System.out.println("Case 1: Login");
                login = new Daniel.Panel_Login();
                this.add(login);
                login.setVisible(true);
                intro.setVisible(false);
                break;
            case 2: //Grab data from login panel
                boardingNumber = login.getjText_boarding();
                nickname = login.getjText_nickname();
                password = "EH270";

                if (password.equals(boardingNumber)) 
                {
                    System.out.println("Password correct");

                    //go on to character selection
                    characterselection = new Panel_CharacterSelection();
                    this.add(characterselection);
                    characterselection.setVisible(true);
                    login.setVisible(false);
                    jLabel_next.setVisible(false);
                    //currentPanel++;
                    System.out.println("Current panel is:" + currentPanel);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Incorrect boarding number");
                    wrongPassword = true;
                    currentPanel = 1;
                }
                break;
            case 3: //QuizRules
                //Add person object
                Person p = new Person(boardingNumber, nickname, characterselection.getType());
                System.out.println(characterselection.getType());
                System.out.println(p);
                
                System.out.println("Case 3: Quiz rules");
                quizrules = new Panel_QuizRules();
                this.add(quizrules);
                characterselection.setVisible(false);
                quizrules.setVisible(true);
                break;
            case 4: //Timer-click
                System.out.println("Case 4: Timer click");
                timerclick = new Panel_TimerClick();
                this.add(timerclick);
                quizrules.setVisible(false);
                timerclick.setVisible(true);
                jLabel_next.setVisible(false);
                break;
            case 5: //Game-statistics (optional)
                System.out.println("Case 5: Game statistics");
            case 6: //Highscore
                System.out.println("Case 6: Highscore");
                highscore = new Panel_Highscore();
                break;
        }

    }//GEN-LAST:event_jLabel_nextMousePressed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    //public void chec
    //public void

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel_next;
    // End of variables declaration//GEN-END:variables
}
