/**
 * @author Tobias
 */
package Tobias;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class GUI_Main extends javax.swing.JFrame {

    private final ImageIcon next_unselected_icon = new ImageIcon ("./art/images/icons/next_unselected.png");
    private final ImageIcon next_entered_icon = new ImageIcon ("./art/images/icons/next_entered.png");
    private final ImageIcon next_pressed_icon = new ImageIcon ("./art/images/icons/next_pressed.png");
    Panel_Intro intro;
    Panel_QuizRules quizrules;
    Panel_CharacterSelection characterselection;
    Panel_TimerClick timerclick;
    Panel_Highscore highscore;
    
    public static JLabel jLabelTest; 
    
    int currentPanel = 0;
    
    public GUI_Main() {
        
        jLabelTest =  new JLabel(next_unselected_icon);
        
        //init icons
        try {
        jLabel_next.setIcon(next_unselected_icon);
        } catch (NullPointerException e) {
            System.out.println("Something wierd just happened!");
        }
            
        initComponents();
        getContentPane().setBackground(Color.orange);
        //jLabel_next.setVisible(true);
        
       // GUI_Main main = new GUI_Main();
        intro = new Panel_Intro();

        this.setLayout(new BorderLayout());
        this.add(intro, BorderLayout.CENTER);
        this.setVisible(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_next = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Destination Game");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel_next.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tobias\\Desktop\\Tobias dropbox\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\icons\\next_unselected.png")); // NOI18N
        jLabel_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseExited(evt);
            }
        });
        getContentPane().add(jLabel_next);
        jLabel_next.setBounds(650, 460, 110, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseEntered
        jLabel_next.setIcon(next_entered_icon);
    }//GEN-LAST:event_jLabel_nextMouseEntered

    private void jLabel_nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseExited
        jLabel_next.setIcon(next_unselected_icon);
    }//GEN-LAST:event_jLabel_nextMouseExited

    private void jLabel_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseClicked
        currentPanel++;
        System.out.println("Current panel is: " + currentPanel);
        
       
        switch (currentPanel) 
        {
            case 0: //Panel_intro which is not relevant
                System.out.println("Case 0!");
            case 1: //CharacterSelection
                System.out.println("Case 1!");
               // System.out.println("Current panel is: " + currentPanel);
                characterselection = new Panel_CharacterSelection();
                this.add(characterselection);
                characterselection.setVisible(true);
                intro.setVisible(false);
                jLabel_next.setVisible(false);
                break;
            case 2: //QuizRules
                System.out.println("Case 2!");
                quizrules = new Panel_QuizRules();
                this.add(quizrules);
                characterselection.setVisible(false);
                quizrules.setVisible(true);
                break;
            case 3: //Timer-click
                System.out.println("Case 3!");
                timerclick = new Panel_TimerClick();
                this.add(timerclick);
                quizrules.setVisible(false);
                timerclick.setVisible(true);
                jLabel_next.setVisible(false);
                break;
            case 4: //Game-statistics
            case 5: //Highscore    
                System.out.println("Case 5!");
                highscore = new Panel_Highscore();
        }
       
            
       
    }//GEN-LAST:event_jLabel_nextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }
    
    public void getJlabel_next() {
        
    }
    
    //public void

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel_next;
    // End of variables declaration//GEN-END:variables
}
