/**
 * @author Tobias
 */
package Tobias;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Panel_CharacterSelection extends javax.swing.JPanel {

    private final ImageIcon man_unselected_icon = new ImageIcon("./art/images/character/man_1_unselected.png");
    private final ImageIcon man_entered_icon = new ImageIcon("./art/images/character/man_1_entered.png");
    private final ImageIcon man_selected_icon = new ImageIcon("./art/images/character/man_1_selected.png");

    private final ImageIcon woman_unselected_icon = new ImageIcon("./art/images/character/woman_1_unselected.png");
    private final ImageIcon woman_entered_icon = new ImageIcon("./art/images/character/woman_1_entered.png");
    private final ImageIcon woman_selected_icon = new ImageIcon("./art/images/character/woman_1_selected.png");

    private final ImageIcon child_unselected_icon = new ImageIcon("./art/images/character/child_1_unselected.png");
    private final ImageIcon child_entered_icon = new ImageIcon("./art/images/character/child_1_entered.png");
    private final ImageIcon child_selected_icon = new ImageIcon("./art/images/character/child_1_selected.png");

    private Boolean man_selected = false;
    private Boolean woman_selected = false;
    private Boolean child_selected = false;

    String type;

    public Panel_CharacterSelection() {
        initComponents();

        //init icons
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_choose1 = new javax.swing.JLabel();
        jLabel_man = new javax.swing.JLabel();
        jLabel_woman = new javax.swing.JLabel();
        jLabel_child = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);

        jLabel_choose1.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jLabel_choose1.setText("Please choose a character");

        jLabel_man.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\man_1_unselected.png")); // NOI18N
        jLabel_man.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_manMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_manMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_manMousePressed(evt);
            }
        });

        jLabel_woman.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\woman_1_unselected.png")); // NOI18N
        jLabel_woman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_womanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_womanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_womanMousePressed(evt);
            }
        });

        jLabel_child.setIcon(new javax.swing.ImageIcon("E:\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\character\\child_1_unselected.png")); // NOI18N
        jLabel_child.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_childMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_childMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_childMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel_choose1)
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(109, 109, 109)
                    .addComponent(jLabel_man)
                    .addGap(78, 78, 78)
                    .addComponent(jLabel_woman)
                    .addGap(83, 83, 83)
                    .addComponent(jLabel_child)
                    .addContainerGap(110, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel_choose1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(439, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(230, 230, 230)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_woman)
                        .addComponent(jLabel_child)
                        .addComponent(jLabel_man))
                    .addContainerGap(230, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_manMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMouseEntered
        if (man_selected != true) {
            jLabel_man.setIcon(man_entered_icon);
        }
    }//GEN-LAST:event_jLabel_manMouseEntered

    private void jLabel_manMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMouseExited
        if (man_selected != true) {
            jLabel_man.setIcon(man_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_manMouseExited

    private void jLabel_manMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_manMousePressed
        jLabel_man.setIcon(man_selected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);
        man_selected = true;
        woman_selected = false;
        child_selected = false;
        GUI_Main.jLabel_next.setVisible(true);
    }//GEN-LAST:event_jLabel_manMousePressed

    private void jLabel_womanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMouseEntered
        if (woman_selected != true) {
            jLabel_woman.setIcon(woman_entered_icon);
        }
    }//GEN-LAST:event_jLabel_womanMouseEntered

    private void jLabel_womanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMouseExited
        if (woman_selected != true) {
            jLabel_woman.setIcon(woman_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_womanMouseExited

    private void jLabel_womanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_womanMousePressed
        jLabel_woman.setIcon(woman_selected_icon);
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_child.setIcon(child_unselected_icon);
        woman_selected = true;
        man_selected = false;
        child_selected = false;
        GUI_Main.jLabel_next.setVisible(true);
    }//GEN-LAST:event_jLabel_womanMousePressed

    private void jLabel_childMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMouseEntered
        if (child_selected != true) {
            jLabel_child.setIcon(child_entered_icon);
        }
    }//GEN-LAST:event_jLabel_childMouseEntered

    private void jLabel_childMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMouseExited
        if (child_selected != true) {
            jLabel_child.setIcon(child_unselected_icon);
        }
    }//GEN-LAST:event_jLabel_childMouseExited

    private void jLabel_childMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_childMousePressed
        jLabel_child.setIcon(child_selected_icon);
        jLabel_man.setIcon(man_unselected_icon);
        jLabel_woman.setIcon(woman_unselected_icon);
        child_selected = true;
        man_selected = false;
        woman_selected = false;
        GUI_Main.jLabel_next.setVisible(true);

    }//GEN-LAST:event_jLabel_childMousePressed

    public String getType() {

        if (man_selected == true) {
            type = "man";
            return type;
        } else if (woman_selected == true) {
            type = "woman";
            return type;
        } else if (child_selected == true) {
            type = "child";

        }
        System.out.println("Type is:" + type);
        return type;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_child;
    private javax.swing.JLabel jLabel_choose1;
    private javax.swing.JLabel jLabel_man;
    private javax.swing.JLabel jLabel_woman;
    // End of variables declaration//GEN-END:variables
}
