/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Andreas;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Andreas Styltsvig
 */
public class Panel_QuizGUI extends javax.swing.JPanel {

    QuizControl quiz;
    boolean done;

    /**
     * Creates new form Panel_QuizGUI
     */
    public Panel_QuizGUI(QuizControl quiz) {

        initComponents();
        jPlayVideoButton.setVisible(false);
        this.quiz = quiz;
        setQuiz();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jQuestion = new javax.swing.JLabel();
        jAnswer1 = new javax.swing.JRadioButton();
        jAnswer2 = new javax.swing.JRadioButton();
        jAnswer3 = new javax.swing.JRadioButton();
        jAnswer4 = new javax.swing.JRadioButton();
        jPictureLabel1 = new javax.swing.JLabel();
        jPictureLabel2 = new javax.swing.JLabel();
        jPictureLabel3 = new javax.swing.JLabel();
        jPictureLabel4 = new javax.swing.JLabel();
        jNextButton = new javax.swing.JButton();
        jPlayVideoButton = new javax.swing.JButton();
        jMainImage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jQuestion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jQuestion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 797, 85));

        buttonGroup1.add(jAnswer1);
        add(jAnswer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        buttonGroup1.add(jAnswer2);
        jAnswer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnswer2ActionPerformed(evt);
            }
        });
        add(jAnswer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        buttonGroup1.add(jAnswer3);
        add(jAnswer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        buttonGroup1.add(jAnswer4);
        add(jAnswer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jPictureLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPictureLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPictureLabel1.setIconTextGap(50);
        add(jPictureLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 140, 140));

        jPictureLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPictureLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPictureLabel2.setIconTextGap(50);
        add(jPictureLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 140, 140));

        jPictureLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPictureLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPictureLabel3.setIconTextGap(50);
        add(jPictureLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 140, 140));

        jPictureLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPictureLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPictureLabel4.setIconTextGap(50);
        add(jPictureLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 140, 140));

        jNextButton.setText("Next");
        jNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextButtonActionPerformed(evt);
            }
        });
        add(jNextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1109, 446, -1, -1));

        jPlayVideoButton.setText("Play Video!");
        jPlayVideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayVideoButtonActionPerformed(evt);
            }
        });
        add(jPlayVideoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, -1, -1));

        jMainImage.setText("                                                ");
        jMainImage.setToolTipText("");
        jMainImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMainImage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        add(jMainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 310, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void jAnswer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnswer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAnswer2ActionPerformed

    private void jNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextButtonActionPerformed
        if (compareButtonAndRightAnswer()) {
            jPlayVideoButton.setVisible(false);
            jMainImage.setVisible(false);
            //setQuiz();
            this.setVisible(false);

        }
    }//GEN-LAST:event_jNextButtonActionPerformed

    private void jPlayVideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayVideoButtonActionPerformed
        try {
            Desktop.getDesktop().browse(new URL(quiz.getQuizTypeUrl()).toURI());
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(Panel_QuizGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPlayVideoButtonActionPerformed

    public boolean compareButtonAndRightAnswer() {
        if (jAnswer1.isSelected()) {
            String text = jAnswer1.getText();
            boolean result = text.equals(quiz.getRightAnswer());
            quiz.setStatistics(text, result);

            return result;
        }
        if (jAnswer2.isSelected()) {
            String text = jAnswer2.getText();
            boolean result = text.equals(quiz.getRightAnswer());
            quiz.setStatistics(text, result);

            return result;
        }
        if (jAnswer3.isSelected()) {

            String text = jAnswer3.getText();
            boolean result = text.equals(quiz.getRightAnswer());
            quiz.setStatistics(text, result);

            return result;
        }
        if (jAnswer4.isSelected()) {

            String text = jAnswer4.getText();
            boolean result = text.equals(quiz.getRightAnswer());
            quiz.setStatistics(text, result);

            return result;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public void setQuiz() {
        quiz.getFile(quiz.getRandomFile());

        String quizType = quiz.getQuiztype();

        switch (quizType) {
            case "picture":
                ImageIcon mainImage = new ImageIcon(quiz.getQuizTypeUrl());
                jMainImage.setIcon(mainImage);
                jMainImage.setVisible(true);
                break;
            case "video":
                jPlayVideoButton.setVisible(true);
                break;
            case "soundClip":
                break;
            default:
                break;
        }

        jQuestion.setText(quiz.getQuestion());
        jAnswer1.setText(quiz.getAnswer().get(0));
        jAnswer2.setText(quiz.getAnswer().get(1));
        jAnswer3.setText(quiz.getAnswer().get(2));
        jAnswer4.setText(quiz.getAnswer().get(3));

        if (quiz.getURLS().get(0).isEmpty()) {

            jPictureLabel1.setBorder(null);
            jPictureLabel2.setBorder(null);
            jAnswer2.setLocation(110, 200);
            jPictureLabel3.setBorder(null);;
            jPictureLabel4.setBorder(null);

        } else {
            ImageIcon selectImage = new ImageIcon(quiz.getURLS().get(0));
            System.out.println(selectImage);
            jPictureLabel1.setIcon(selectImage);
            jPictureLabel1.setSize(selectImage.getIconWidth(), selectImage.getIconHeight());

            ImageIcon selectImage2 = new ImageIcon(quiz.getURLS().get(1));
            jPictureLabel2.setIcon(selectImage2);
            jPictureLabel2.setSize(selectImage2.getIconWidth(), selectImage2.getIconHeight());

            ImageIcon selectImage3 = new ImageIcon(quiz.getURLS().get(2));
            jPictureLabel3.setIcon(selectImage3);
            jPictureLabel3.setSize(selectImage3.getIconWidth(), selectImage3.getIconHeight());

            ImageIcon selectImage4 = new ImageIcon(quiz.getURLS().get(3));
            jPictureLabel4.setIcon(selectImage4);
            jPictureLabel4.setSize(selectImage4.getIconWidth(), selectImage4.getIconHeight());

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jAnswer1;
    private javax.swing.JRadioButton jAnswer2;
    private javax.swing.JRadioButton jAnswer3;
    private javax.swing.JRadioButton jAnswer4;
    private javax.swing.JLabel jMainImage;
    private javax.swing.JButton jNextButton;
    private javax.swing.JLabel jPictureLabel1;
    private javax.swing.JLabel jPictureLabel2;
    private javax.swing.JLabel jPictureLabel3;
    private javax.swing.JLabel jPictureLabel4;
    private javax.swing.JButton jPlayVideoButton;
    private javax.swing.JLabel jQuestion;
    // End of variables declaration//GEN-END:variables
}
