package Daniel;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 * @author Tobias
 */

public class Panel_Login extends javax.swing.JPanel {
    
    private final ImageIcon ticket = new ImageIcon("./art/images/icon/flightTicket.png");
    private ArrayList<Person> list;

    public Panel_Login() {
        initComponents();
        
        // load the list at startup. Is this nescessary?
        this.list = FileHandler.load("text.txt"); 
        
        //init icons
        jLabel_flightTicket.setIcon(ticket);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_username = new javax.swing.JLabel();
        jLabel_nickname = new javax.swing.JLabel();
        jText_boarding = new javax.swing.JTextField();
        jText_nickname = new javax.swing.JTextField();
        jLabel_text1 = new javax.swing.JLabel();
        jLabel_text2 = new javax.swing.JLabel();
        jLabel_flightTicket = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setOpaque(false);

        jLabel_username.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel_username.setText("Boardingnumber");

        jLabel_nickname.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel_nickname.setText("Nickname");

        jText_boarding.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jText_boarding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_boardingActionPerformed(evt);
            }
        });

        jText_nickname.setFont(new java.awt.Font("Tunga", 0, 18)); // NOI18N
        jText_nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_nicknameActionPerformed(evt);
            }
        });

        jLabel_text1.setFont(new java.awt.Font("Tunga", 1, 48)); // NOI18N
        jLabel_text1.setText("LOGIN WITH YOUR");

        jLabel_text2.setFont(new java.awt.Font("Tunga", 1, 48)); // NOI18N
        jLabel_text2.setText("FLIGHT TICKET");

        jLabel_flightTicket.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tobias\\Desktop\\Tobias dropbox\\Dropbox\\Datamatiker\\1. semester\\Programming\\JAVA\\Obligatoriske afleveringer\\4_DAT-Service\\DSQuizGame\\art\\images\\icons\\flightTicket.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel_text1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel_text2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_nickname)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel_username)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText_boarding, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(jText_nickname))))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_flightTicket)
                .addGap(311, 311, 311))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_username)
                    .addComponent(jText_boarding, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jText_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nickname))
                .addGap(74, 74, 74)
                .addComponent(jLabel_flightTicket)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jText_boardingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_boardingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_boardingActionPerformed

    private void jText_nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_nicknameActionPerformed
    
    public String getjText_boarding() {
        String text = jText_boarding.getText();
        return text;
    }
    
    public void setjText_boarding() {
        jText_boarding.setText("");
    }
    
    public String getjText_nickname() {
        String text = jText_nickname.getText();
        return text;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_flightTicket;
    private javax.swing.JLabel jLabel_nickname;
    private javax.swing.JLabel jLabel_text1;
    private javax.swing.JLabel jLabel_text2;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JTextField jText_boarding;
    private javax.swing.JTextField jText_nickname;
    // End of variables declaration//GEN-END:variables
}
